---
- hosts: localhost
  gather_facts: False
  roles:
    - { role: 2cld-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}

- hosts: tocld-psmaster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: 2cld-defaults}
